/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface TestMenu {}
}

declare global {


  interface HTMLTestMenuElement extends Components.TestMenu, HTMLStencilElement {}
  var HTMLTestMenuElement: {
    prototype: HTMLTestMenuElement;
    new (): HTMLTestMenuElement;
  };
  interface HTMLElementTagNameMap {
    'test-menu': HTMLTestMenuElement;
  }
}

declare namespace LocalJSX {
  interface TestMenu extends JSXBase.HTMLAttributes<HTMLTestMenuElement> {}

  interface IntrinsicElements {
    'test-menu': TestMenu;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


